package com.mogujie.tt.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mogujie.tt.DB.entity.DetailDispEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DetailDispInfo.
*/
public class DetailDispDao extends AbstractDao<DetailDispEntity, Long> {

    public static final String TABLENAME = "DetailDispInfo";

    /**
     * Properties of entity DetailDispEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property TrafficType = new Property(5, int.class, "trafficType", false, "TRAFFIC_TYPE");
        public final static Property Time = new Property(6, String.class, "time", false, "TIME");
        public final static Property Start = new Property(7, String.class, "start", false, "START");
        public final static Property End = new Property(8, String.class, "end", false, "END");
        public final static Property Version = new Property(9, int.class, "version", false, "VERSION");
        public final static Property Status = new Property(10, int.class, "status", false, "STATUS");
        public final static Property Created = new Property(11, int.class, "created", false, "CREATED");
        public final static Property Updated = new Property(12, int.class, "updated", false, "UPDATED");
    };


    public DetailDispDao(DaoConfig config) {
        super(config);
    }
    
    public DetailDispDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DetailDispInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TYPE' INTEGER NOT NULL ," + // 1: type
                "'IMAGE' TEXT NOT NULL ," + // 2: image
                "'TITLE' TEXT NOT NULL ," + // 3: title
                "'CONTENT' TEXT NOT NULL ," + // 4: content
                "'TRAFFIC_TYPE' INTEGER NOT NULL ," + // 5: trafficType
                "'TIME' TEXT NOT NULL ," + // 6: time
                "'START' TEXT NOT NULL ," + // 7: start
                "'END' TEXT NOT NULL ," + // 8: end
                "'VERSION' INTEGER NOT NULL ," + // 9: version
                "'STATUS' INTEGER NOT NULL ," + // 10: status
                "'CREATED' INTEGER NOT NULL ," + // 11: created
                "'UPDATED' INTEGER NOT NULL );"); // 12: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DetailDispInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DetailDispEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getType());
        stmt.bindString(3, entity.getImage());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getContent());
        stmt.bindLong(6, entity.getTrafficType());
        stmt.bindString(7, entity.getTime());
        stmt.bindString(8, entity.getStart());
        stmt.bindString(9, entity.getEnd());
        stmt.bindLong(10, entity.getVersion());
        stmt.bindLong(11, entity.getStatus());
        stmt.bindLong(12, entity.getCreated());
        stmt.bindLong(13, entity.getUpdated());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DetailDispEntity readEntity(Cursor cursor, int offset) {
        DetailDispEntity entity = new DetailDispEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.getString(offset + 2), // image
            cursor.getString(offset + 3), // title
            cursor.getString(offset + 4), // content
            cursor.getInt(offset + 5), // trafficType
            cursor.getString(offset + 6), // time
            cursor.getString(offset + 7), // start
            cursor.getString(offset + 8), // end
            cursor.getInt(offset + 9), // version
            cursor.getInt(offset + 10), // status
            cursor.getInt(offset + 11), // created
            cursor.getInt(offset + 12) // updated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DetailDispEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setImage(cursor.getString(offset + 2));
        entity.setTitle(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
        entity.setTrafficType(cursor.getInt(offset + 5));
        entity.setTime(cursor.getString(offset + 6));
        entity.setStart(cursor.getString(offset + 7));
        entity.setEnd(cursor.getString(offset + 8));
        entity.setVersion(cursor.getInt(offset + 9));
        entity.setStatus(cursor.getInt(offset + 10));
        entity.setCreated(cursor.getInt(offset + 11));
        entity.setUpdated(cursor.getInt(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DetailDispEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DetailDispEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
