package com.mogujie.tt.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mogujie.tt.DB.entity.PlayConfigEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PlayConfigInfo.
*/
public class PlayConfigDao extends AbstractDao<PlayConfigEntity, Long> {

    public static final String TABLENAME = "PlayConfigInfo";

    /**
     * Properties of entity PlayConfigEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CityName = new Property(1, String.class, "cityName", false, "CITY_NAME");
        public final static Property Quality = new Property(2, int.class, "quality", false, "QUALITY");
        public final static Property StartTime = new Property(3, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(4, String.class, "endTime", false, "END_TIME");
        public final static Property TransportToolType = new Property(5, int.class, "transportToolType", false, "TRANSPORT_TOOL_TYPE");
        public final static Property Position = new Property(6, int.class, "position", false, "POSITION");
        public final static Property Version = new Property(7, int.class, "version", false, "VERSION");
        public final static Property Status = new Property(8, int.class, "status", false, "STATUS");
        public final static Property Created = new Property(9, int.class, "created", false, "CREATED");
        public final static Property Updated = new Property(10, int.class, "updated", false, "UPDATED");
    };


    public PlayConfigDao(DaoConfig config) {
        super(config);
    }
    
    public PlayConfigDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PlayConfigInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CITY_NAME' TEXT NOT NULL ," + // 1: cityName
                "'QUALITY' INTEGER NOT NULL ," + // 2: quality
                "'START_TIME' TEXT NOT NULL ," + // 3: startTime
                "'END_TIME' TEXT NOT NULL ," + // 4: endTime
                "'TRANSPORT_TOOL_TYPE' INTEGER NOT NULL ," + // 5: transportToolType
                "'POSITION' INTEGER NOT NULL ," + // 6: position
                "'VERSION' INTEGER NOT NULL ," + // 7: version
                "'STATUS' INTEGER NOT NULL ," + // 8: status
                "'CREATED' INTEGER NOT NULL ," + // 9: created
                "'UPDATED' INTEGER NOT NULL );"); // 10: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PlayConfigInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlayConfigEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCityName());
        stmt.bindLong(3, entity.getQuality());
        stmt.bindString(4, entity.getStartTime());
        stmt.bindString(5, entity.getEndTime());
        stmt.bindLong(6, entity.getTransportToolType());
        stmt.bindLong(7, entity.getPosition());
        stmt.bindLong(8, entity.getVersion());
        stmt.bindLong(9, entity.getStatus());
        stmt.bindLong(10, entity.getCreated());
        stmt.bindLong(11, entity.getUpdated());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlayConfigEntity readEntity(Cursor cursor, int offset) {
        PlayConfigEntity entity = new PlayConfigEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // cityName
            cursor.getInt(offset + 2), // quality
            cursor.getString(offset + 3), // startTime
            cursor.getString(offset + 4), // endTime
            cursor.getInt(offset + 5), // transportToolType
            cursor.getInt(offset + 6), // position
            cursor.getInt(offset + 7), // version
            cursor.getInt(offset + 8), // status
            cursor.getInt(offset + 9), // created
            cursor.getInt(offset + 10) // updated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlayConfigEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityName(cursor.getString(offset + 1));
        entity.setQuality(cursor.getInt(offset + 2));
        entity.setStartTime(cursor.getString(offset + 3));
        entity.setEndTime(cursor.getString(offset + 4));
        entity.setTransportToolType(cursor.getInt(offset + 5));
        entity.setPosition(cursor.getInt(offset + 6));
        entity.setVersion(cursor.getInt(offset + 7));
        entity.setStatus(cursor.getInt(offset + 8));
        entity.setCreated(cursor.getInt(offset + 9));
        entity.setUpdated(cursor.getInt(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PlayConfigEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PlayConfigEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
