package com.mogujie.tt.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mogujie.tt.DB.entity.SightEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SightInfo.
*/
public class SightDao extends AbstractDao<SightEntity, Long> {

    public static final String TABLENAME = "SightInfo";

    /**
     * Properties of entity SightEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PeerId = new Property(1, int.class, "peerId", false, "PEER_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Pic = new Property(3, String.class, "pic", false, "PIC");
        public final static Property Star = new Property(4, int.class, "star", false, "STAR");
        public final static Property Tag = new Property(5, String.class, "tag", false, "TAG");
        public final static Property Free = new Property(6, int.class, "free", false, "FREE");
        public final static Property MustGo = new Property(7, int.class, "mustGo", false, "MUST_GO");
        public final static Property Select = new Property(8, int.class, "select", false, "SELECT");
        public final static Property Focus = new Property(9, int.class, "focus", false, "FOCUS");
        public final static Property Version = new Property(10, int.class, "version", false, "VERSION");
        public final static Property Status = new Property(11, int.class, "status", false, "STATUS");
        public final static Property Created = new Property(12, int.class, "created", false, "CREATED");
        public final static Property Updated = new Property(13, int.class, "updated", false, "UPDATED");
    };


    public SightDao(DaoConfig config) {
        super(config);
    }
    
    public SightDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SightInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PEER_ID' INTEGER NOT NULL UNIQUE ," + // 1: peerId
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'PIC' TEXT NOT NULL ," + // 3: pic
                "'STAR' INTEGER NOT NULL ," + // 4: star
                "'TAG' TEXT NOT NULL ," + // 5: tag
                "'FREE' INTEGER NOT NULL ," + // 6: free
                "'MUST_GO' INTEGER NOT NULL ," + // 7: mustGo
                "'SELECT' INTEGER NOT NULL ," + // 8: select
                "'FOCUS' INTEGER NOT NULL ," + // 9: focus
                "'VERSION' INTEGER NOT NULL ," + // 10: version
                "'STATUS' INTEGER NOT NULL ," + // 11: status
                "'CREATED' INTEGER NOT NULL ," + // 12: created
                "'UPDATED' INTEGER NOT NULL );"); // 13: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SightInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SightEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPeerId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getPic());
        stmt.bindLong(5, entity.getStar());
        stmt.bindString(6, entity.getTag());
        stmt.bindLong(7, entity.getFree());
        stmt.bindLong(8, entity.getMustGo());
        stmt.bindLong(9, entity.getSelect());
        stmt.bindLong(10, entity.getFocus());
        stmt.bindLong(11, entity.getVersion());
        stmt.bindLong(12, entity.getStatus());
        stmt.bindLong(13, entity.getCreated());
        stmt.bindLong(14, entity.getUpdated());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SightEntity readEntity(Cursor cursor, int offset) {
        SightEntity entity = new SightEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // peerId
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // pic
            cursor.getInt(offset + 4), // star
            cursor.getString(offset + 5), // tag
            cursor.getInt(offset + 6), // free
            cursor.getInt(offset + 7), // mustGo
            cursor.getInt(offset + 8), // select
            cursor.getInt(offset + 9), // focus
            cursor.getInt(offset + 10), // version
            cursor.getInt(offset + 11), // status
            cursor.getInt(offset + 12), // created
            cursor.getInt(offset + 13) // updated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SightEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeerId(cursor.getInt(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setPic(cursor.getString(offset + 3));
        entity.setStar(cursor.getInt(offset + 4));
        entity.setTag(cursor.getString(offset + 5));
        entity.setFree(cursor.getInt(offset + 6));
        entity.setMustGo(cursor.getInt(offset + 7));
        entity.setSelect(cursor.getInt(offset + 8));
        entity.setFocus(cursor.getInt(offset + 9));
        entity.setVersion(cursor.getInt(offset + 10));
        entity.setStatus(cursor.getInt(offset + 11));
        entity.setCreated(cursor.getInt(offset + 12));
        entity.setUpdated(cursor.getInt(offset + 13));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SightEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SightEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
