package com.mogujie.tt.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mogujie.tt.DB.entity.SightEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SightInfo.
*/
public class SightDao extends AbstractDao<SightEntity, Long> {

    public static final String TABLENAME = "SightInfo";

    /**
     * Properties of entity SightEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PeerId = new Property(1, int.class, "peerId", false, "PEER_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Pic = new Property(3, String.class, "pic", false, "PIC");
        public final static Property Star = new Property(4, int.class, "star", false, "STAR");
        public final static Property Tag = new Property(5, String.class, "tag", false, "TAG");
        public final static Property Free = new Property(6, int.class, "free", false, "FREE");
        public final static Property MustGo = new Property(7, int.class, "mustGo", false, "MUST_GO");
        public final static Property Url = new Property(8, String.class, "url", false, "URL");
        public final static Property PlayTime = new Property(9, int.class, "playTime", false, "PLAY_TIME");
        public final static Property Price = new Property(10, int.class, "price", false, "PRICE");
        public final static Property BestStartTime = new Property(11, String.class, "bestStartTime", false, "BEST_START_TIME");
        public final static Property BestEndTime = new Property(12, String.class, "bestEndTime", false, "BEST_END_TIME");
        public final static Property StartTime = new Property(13, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(14, String.class, "endTime", false, "END_TIME");
        public final static Property Select = new Property(15, int.class, "select", false, "SELECT");
        public final static Property Version = new Property(16, int.class, "version", false, "VERSION");
        public final static Property Status = new Property(17, int.class, "status", false, "STATUS");
        public final static Property Created = new Property(18, int.class, "created", false, "CREATED");
        public final static Property Updated = new Property(19, int.class, "updated", false, "UPDATED");
    };


    public SightDao(DaoConfig config) {
        super(config);
    }
    
    public SightDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SightInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PEER_ID' INTEGER NOT NULL UNIQUE ," + // 1: peerId
                "'NAME' TEXT NOT NULL ," + // 2: name
                "'PIC' TEXT NOT NULL ," + // 3: pic
                "'STAR' INTEGER NOT NULL ," + // 4: star
                "'TAG' TEXT NOT NULL ," + // 5: tag
                "'FREE' INTEGER NOT NULL ," + // 6: free
                "'MUST_GO' INTEGER NOT NULL ," + // 7: mustGo
                "'URL' TEXT NOT NULL ," + // 8: url
                "'PLAY_TIME' INTEGER NOT NULL ," + // 9: playTime
                "'PRICE' INTEGER NOT NULL ," + // 10: price
                "'BEST_START_TIME' TEXT NOT NULL ," + // 11: bestStartTime
                "'BEST_END_TIME' TEXT NOT NULL ," + // 12: bestEndTime
                "'START_TIME' TEXT NOT NULL ," + // 13: startTime
                "'END_TIME' TEXT NOT NULL ," + // 14: endTime
                "'SELECT' INTEGER NOT NULL ," + // 15: select
                "'VERSION' INTEGER NOT NULL ," + // 16: version
                "'STATUS' INTEGER NOT NULL ," + // 17: status
                "'CREATED' INTEGER NOT NULL ," + // 18: created
                "'UPDATED' INTEGER NOT NULL );"); // 19: updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SightInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SightEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPeerId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getPic());
        stmt.bindLong(5, entity.getStar());
        stmt.bindString(6, entity.getTag());
        stmt.bindLong(7, entity.getFree());
        stmt.bindLong(8, entity.getMustGo());
        stmt.bindString(9, entity.getUrl());
        stmt.bindLong(10, entity.getPlayTime());
        stmt.bindLong(11, entity.getPrice());
        stmt.bindString(12, entity.getBestStartTime());
        stmt.bindString(13, entity.getBestEndTime());
        stmt.bindString(14, entity.getStartTime());
        stmt.bindString(15, entity.getEndTime());
        stmt.bindLong(16, entity.getSelect());
        stmt.bindLong(17, entity.getVersion());
        stmt.bindLong(18, entity.getStatus());
        stmt.bindLong(19, entity.getCreated());
        stmt.bindLong(20, entity.getUpdated());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SightEntity readEntity(Cursor cursor, int offset) {
        SightEntity entity = new SightEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // peerId
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // pic
            cursor.getInt(offset + 4), // star
            cursor.getString(offset + 5), // tag
            cursor.getInt(offset + 6), // free
            cursor.getInt(offset + 7), // mustGo
            cursor.getString(offset + 8), // url
            cursor.getInt(offset + 9), // playTime
            cursor.getInt(offset + 10), // price
            cursor.getString(offset + 11), // bestStartTime
            cursor.getString(offset + 12), // bestEndTime
            cursor.getString(offset + 13), // startTime
            cursor.getString(offset + 14), // endTime
            cursor.getInt(offset + 15), // select
            cursor.getInt(offset + 16), // version
            cursor.getInt(offset + 17), // status
            cursor.getInt(offset + 18), // created
            cursor.getInt(offset + 19) // updated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SightEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeerId(cursor.getInt(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setPic(cursor.getString(offset + 3));
        entity.setStar(cursor.getInt(offset + 4));
        entity.setTag(cursor.getString(offset + 5));
        entity.setFree(cursor.getInt(offset + 6));
        entity.setMustGo(cursor.getInt(offset + 7));
        entity.setUrl(cursor.getString(offset + 8));
        entity.setPlayTime(cursor.getInt(offset + 9));
        entity.setPrice(cursor.getInt(offset + 10));
        entity.setBestStartTime(cursor.getString(offset + 11));
        entity.setBestEndTime(cursor.getString(offset + 12));
        entity.setStartTime(cursor.getString(offset + 13));
        entity.setEndTime(cursor.getString(offset + 14));
        entity.setSelect(cursor.getInt(offset + 15));
        entity.setVersion(cursor.getInt(offset + 16));
        entity.setStatus(cursor.getInt(offset + 17));
        entity.setCreated(cursor.getInt(offset + 18));
        entity.setUpdated(cursor.getInt(offset + 19));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SightEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SightEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
