package com.mogujie.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PlayConfigInfo.
 */
public class PlayConfigEntity {

    private Long id;
    /** Not-null value. */
    private String cityName;
    private int quality;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;
    private int transportToolType;
    private int position;
    private int version;
    private int status;
    private int created;
    private int updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PlayConfigEntity() {
    }

    public PlayConfigEntity(Long id) {
        this.id = id;
    }

    public PlayConfigEntity(Long id, String cityName, int quality, String startTime, String endTime, int transportToolType, int position, int version, int status, int created, int updated) {
        this.id = id;
        this.cityName = cityName;
        this.quality = quality;
        this.startTime = startTime;
        this.endTime = endTime;
        this.transportToolType = transportToolType;
        this.position = position;
        this.version = version;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCityName() {
        return cityName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public int getQuality() {
        return quality;
    }

    public void setQuality(int quality) {
        this.quality = quality;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public int getTransportToolType() {
        return transportToolType;
    }

    public void setTransportToolType(int transportToolType) {
        this.transportToolType = transportToolType;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
