package com.mogujie.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SightInfo.
 */
public class SightEntity {

    private Long id;
    private int peerId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String pic;
    private int star;
    /** Not-null value. */
    private String tag;
    private int free;
    private int mustGo;
    /** Not-null value. */
    private String url;
    private int playTime;
    private int price;
    /** Not-null value. */
    private String bestStartTime;
    /** Not-null value. */
    private String bestEndTime;
    private int select;
    private int version;
    private int status;
    private int created;
    private int updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SightEntity() {
    }

    public SightEntity(Long id) {
        this.id = id;
    }

    public SightEntity(Long id, int peerId, String name, String pic, int star, String tag, int free, int mustGo, String url, int playTime, int price, String bestStartTime, String bestEndTime, int select, int version, int status, int created, int updated) {
        this.id = id;
        this.peerId = peerId;
        this.name = name;
        this.pic = pic;
        this.star = star;
        this.tag = tag;
        this.free = free;
        this.mustGo = mustGo;
        this.url = url;
        this.playTime = playTime;
        this.price = price;
        this.bestStartTime = bestStartTime;
        this.bestEndTime = bestEndTime;
        this.select = select;
        this.version = version;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPeerId() {
        return peerId;
    }

    public void setPeerId(int peerId) {
        this.peerId = peerId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPic() {
        return pic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPic(String pic) {
        this.pic = pic;
    }

    public int getStar() {
        return star;
    }

    public void setStar(int star) {
        this.star = star;
    }

    /** Not-null value. */
    public String getTag() {
        return tag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag(String tag) {
        this.tag = tag;
    }

    public int getFree() {
        return free;
    }

    public void setFree(int free) {
        this.free = free;
    }

    public int getMustGo() {
        return mustGo;
    }

    public void setMustGo(int mustGo) {
        this.mustGo = mustGo;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public int getPlayTime() {
        return playTime;
    }

    public void setPlayTime(int playTime) {
        this.playTime = playTime;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    /** Not-null value. */
    public String getBestStartTime() {
        return bestStartTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBestStartTime(String bestStartTime) {
        this.bestStartTime = bestStartTime;
    }

    /** Not-null value. */
    public String getBestEndTime() {
        return bestEndTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBestEndTime(String bestEndTime) {
        this.bestEndTime = bestEndTime;
    }

    public int getSelect() {
        return select;
    }

    public void setSelect(int select) {
        this.select = select;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
