package com.mogujie.tt.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TravelInfo.
 */
public class TravelEntity {

    private Long id;
    private int dbId;
    private int creatorId;
    private int duration;
    /** Not-null value. */
    private String startDate;
    /** Not-null value. */
    private String endDate;
    /** Not-null value. */
    private String startPlace;
    /** Not-null value. */
    private String endPlace;
    /** Not-null value. */
    private String destination;
    /** Not-null value. */
    private String destinationBK;
    private int personNum;
    private int trafficWay;
    /** Not-null value. */
    private String trafficStartTime;
    /** Not-null value. */
    private String trafficEndTime;
    private int trafficQuality;
    private int playQuality;
    /** Not-null value. */
    private String playStartTime;
    /** Not-null value. */
    private String playEndTime;
    private int cityTraffic;
    private int hotelPosition;
    private int cost;
    private int version;
    private int status;
    private int created;
    private int updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TravelEntity() {
    }

    public TravelEntity(Long id) {
        this.id = id;
    }

    public TravelEntity(Long id, int dbId, int creatorId, int duration, String startDate, String endDate, String startPlace, String endPlace, String destination, String destinationBK, int personNum, int trafficWay, String trafficStartTime, String trafficEndTime, int trafficQuality, int playQuality, String playStartTime, String playEndTime, int cityTraffic, int hotelPosition, int cost, int version, int status, int created, int updated) {
        this.id = id;
        this.dbId = dbId;
        this.creatorId = creatorId;
        this.duration = duration;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startPlace = startPlace;
        this.endPlace = endPlace;
        this.destination = destination;
        this.destinationBK = destinationBK;
        this.personNum = personNum;
        this.trafficWay = trafficWay;
        this.trafficStartTime = trafficStartTime;
        this.trafficEndTime = trafficEndTime;
        this.trafficQuality = trafficQuality;
        this.playQuality = playQuality;
        this.playStartTime = playStartTime;
        this.playEndTime = playEndTime;
        this.cityTraffic = cityTraffic;
        this.hotelPosition = hotelPosition;
        this.cost = cost;
        this.version = version;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDbId() {
        return dbId;
    }

    public void setDbId(int dbId) {
        this.dbId = dbId;
    }

    public int getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(int creatorId) {
        this.creatorId = creatorId;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    /** Not-null value. */
    public String getStartDate() {
        return startDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /** Not-null value. */
    public String getEndDate() {
        return endDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /** Not-null value. */
    public String getStartPlace() {
        return startPlace;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartPlace(String startPlace) {
        this.startPlace = startPlace;
    }

    /** Not-null value. */
    public String getEndPlace() {
        return endPlace;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndPlace(String endPlace) {
        this.endPlace = endPlace;
    }

    /** Not-null value. */
    public String getDestination() {
        return destination;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /** Not-null value. */
    public String getDestinationBK() {
        return destinationBK;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDestinationBK(String destinationBK) {
        this.destinationBK = destinationBK;
    }

    public int getPersonNum() {
        return personNum;
    }

    public void setPersonNum(int personNum) {
        this.personNum = personNum;
    }

    public int getTrafficWay() {
        return trafficWay;
    }

    public void setTrafficWay(int trafficWay) {
        this.trafficWay = trafficWay;
    }

    /** Not-null value. */
    public String getTrafficStartTime() {
        return trafficStartTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTrafficStartTime(String trafficStartTime) {
        this.trafficStartTime = trafficStartTime;
    }

    /** Not-null value. */
    public String getTrafficEndTime() {
        return trafficEndTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTrafficEndTime(String trafficEndTime) {
        this.trafficEndTime = trafficEndTime;
    }

    public int getTrafficQuality() {
        return trafficQuality;
    }

    public void setTrafficQuality(int trafficQuality) {
        this.trafficQuality = trafficQuality;
    }

    public int getPlayQuality() {
        return playQuality;
    }

    public void setPlayQuality(int playQuality) {
        this.playQuality = playQuality;
    }

    /** Not-null value. */
    public String getPlayStartTime() {
        return playStartTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayStartTime(String playStartTime) {
        this.playStartTime = playStartTime;
    }

    /** Not-null value. */
    public String getPlayEndTime() {
        return playEndTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayEndTime(String playEndTime) {
        this.playEndTime = playEndTime;
    }

    public int getCityTraffic() {
        return cityTraffic;
    }

    public void setCityTraffic(int cityTraffic) {
        this.cityTraffic = cityTraffic;
    }

    public int getHotelPosition() {
        return hotelPosition;
    }

    public void setHotelPosition(int hotelPosition) {
        this.hotelPosition = hotelPosition;
    }

    public int getCost() {
        return cost;
    }

    public void setCost(int cost) {
        this.cost = cost;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
